### ISSUE TITLE
Crashes on empty line

### ISSUE THREAD

**Issue by terrorfisch** [sstadick/hck#11]
Reproduce via `date | hck -f2`

Debug build crashes due to overflow. Release build due to out of range access.

https://old.reddit.com/r/rust/comments/ofa3z3/hck_a_faster_and_more_featureful_cut_replacement/h4by7r0/

https://github.com/sstadick/hck/blob/master/src/lib/core.rs#L288

**Comment by sstadick** [comment]
This has been fixed in v0.3.0. Thanks for making an issue for it! 

Note that I changed the default split value from a literal `\t` to a `\s+` regex, so now 

`date | hck -f2` produces output, but equivalent-to-v0.2.0 `date | hck -Ld'\t' -f2` does what is expected.
