### ISSUE TITLE
Automatic gzip decompression seems not to work, unless pigz is in the path

### ISSUE THREAD

**Issue by ghuls** [sstadick/hck#33]
hck compiled with
```
just install-native
```

This results in garbled characters:
```
# gzip in PATH: This results in garbled characters.
hck -z -f 1 test.gz

# pigz in PATH: Works.
hck -z -f 1 test.gz
```

BTW for the fastest gzip decompression `igzip` of https://github.com/intel/isa-l can be used.

See: https://github.com/zlib-ng/zlib-ng/issues/986 for an example decompression (gzip, pigz with zlib-ng as zlib library and igzip).

**Comment by sstadick** [comment]
Thanks for making an issue! I'll definitely be checking out isa-l!

I've opened a PR here: https://github.com/BurntSushi/ripgrep/pull/1946 with a fix. If that is rejected I'll just vendor it into `hck` and make it do the expected thing. I'll also add `isa-l` as a binary to try to find first in line, then `pigz`, then `gzip` 👍 

I'm not sure how I messed up trying this out before, I definitely thought I tried it with and without `pigz` in the path.

**Comment by ghuls** [comment]
I don't think pigz is (much) faster than gzip when decompressing (or at least not much) gzipped files as the decompression is always single-threaded.(when zlib-ng is used as zlib library, it will beat gzip (didn't try to compile gzip with zlib-ng yet)).

This entry in the table in the README looks wrong to me:
```
*.tbz2 | bzip -d -c | gzip
-- | -- | --
```

**Comment by sstadick** [comment]
Good catch on the readme, fix incoming. I was manually transcribing from here: https://github.com/BurntSushi/ripgrep/blob/9b01a8f9ae53ebcd05c27ec21843758c2c1e823f/crates/cli/src/decompress.rs#L497

Running on ubuntu 20.04, using whatever the apt-get installed versions of gzip and pigz are, pigz seems faster:

```bash
❯ pigz -V
pigz 2.4
❯ /usr/bin/time pigz -d -c hyper_data.txt.gz > /dev/null
17.87user 1.16system 0:13.79elapsed 137%CPU (0avgtext+0avgdata 2452maxresident)k
0inputs+0outputs (0major+135minor)pagefaults 0swaps

❯ gzip -V            
gzip 1.10
Copyright (C) 2018 Free Software Foundation, Inc.
Copyright (C) 1993 Jean-loup Gailly.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <https://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

Written by Jean-loup Gailly.
❯ /usr/bin/time gzip -d -c hyper_data.txt.gz > /dev/null
22.28user 0.20system 0:22.49elapsed 99%CPU (0avgtext+0avgdata 1768maxresident)k
0inputs+0outputs (0major+150minor)pagefaults 0swaps
```

`hyper_data.txt.gz` is just the gzipped benchmark data linked in the readme.

**Comment by sstadick** [comment]
I don't disagree that bespoke compilations of either gzip / pigz will be better than the system installed ones. All I'm aiming for here is "sensible defaults" for decompression. Performance of the decompression itself is secondary since we are already running the decompression in a separate process. This is purely a convenience over `pigz -c -d ./data.tsv.gz | hck`, and in no way more performant than doing exactly that :(

**Comment by sstadick** [comment]
However, for gzip in particular, something I have not yet delved into but want to explore would be doing that decompression in process using a rust lib of some sort to be more performant than reading from stdin. I just haven't had time to explore that option yet.

**Comment by ghuls** [comment]
You have https://github.com/rust-lang/flate2-rs/ which allows you to e.g. choose zlib-ng as zlib library.

**Comment by learnbyexample** [comment]
Not sure if it is related to this issue, but I'm seeing this:

```bash
$ cat chk.csv 
Name,Maths,Physics,Chemistry
Ith,100,100,100
Cy,97,98,95
Lin,78,83,80

# gz input gives garbled result (as mentioned in the issue)
$ gzip chk.csv
$ hck -d, -f2 -z chk.csv.gz
�(�	Ȩ

# renaming it to tgz works!
$ mv chk.csv.gz chk.csv.tgz
$ hck -d, -f2 -z chk.csv.tgz
Maths
100
97
78
```

**Comment by sstadick** [comment]
@learnbyexample, that is indeed related! I'm going to give my PR to `grep_cli` the weekend to see if it gets a response and then go from there. If there isn't a `grep_cli` fix by Monday I'll make a release that drops pigz for now and go from there.

If you install pigz auto-decompression should work (not ideal, i know).

**Comment by sstadick** [comment]
WIP PR for moving to flate2 for some compression types (gzip, mainly). https://github.com/sstadick/hck/pull/34

**Comment by sstadick** [comment]
See release v0.6.1
