### ISSUE TITLE
Windows released binary should have the extension ".exe"

### ISSUE THREAD

**Issue by AntonOks** [sstadick/hck#52]
Please change i.e. ```https://github.com/sstadick/hck/releases/download/v0.7.1/hck-windows-amd64``` to ```https://github.com/sstadick/hck/releases/download/v0.7.1/hck-windows-amd64```**_.exe_** ;)

Thanks :)

**Comment by sstadick** [comment]
Thanks for making an issue! I'll work that into the next release 👍
