### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by 0323pin** [sstadick/hck#58]
Hi,

NetBSD package maintainer and `hck` user here, just curious about this project status.

I understand that `hck` may be feature complete and, as such, it doesn't require regular changes. But, it being a `rust` project, it might be good to bump the dependency crates every now and then.

Regards :)

**Comment by sstadick** [comment]
Hi! I'd view it as mostly complete - it could probably do with a 1.0 release. 

I do need to update the deps and probably set up some automation to keep that going. Was there a specific dependency you view as critical to update?

**Comment by 0323pin** [comment]
Thanks for your reply

> Was there a specific dependency you view as critical to update?

Not really, just curious. I understand it's feature complete, I'm using it on a daily basis and haven't missed anything.
Closing this issue now.
Thanks!

**Comment by sstadick** [comment]
@0323pin I'll work on setting up some automation to keep deps up to date, as well as getting a 1.0 release out. `hck` is using old versions of some of my own crates even and could stand a little maintenance work.

Thank you for making an issue!

**Comment by 0323pin** [comment]
@sstadick Thank you!
