### ISSUE TITLE
Incorrect output column order

### ISSUE THREAD

**Issue by sjneph** [sstadick/hck#59]
Output column order is not always in the specified command-line order when using the attached tab-delimited file as input.
```
# incorrect output order
> hck -F \#ct -F st -F en -F nuc_lengths -F nuc_starts buggy.txt | head -3 
#ct     st      en      nuc_starts      nuc_lengths
...
```

```
# remove "-F st" only 
# correct output order
> hck -F \#ct -F en -F nuc_lengths -F nuc_starts buggy.txt | head -3
#ct     en      nuc_lengths     nuc_starts
...
```

```
# incorrect output order
# remove "-F en" only
> hck -F \#ct -F st -F nuc_lengths -F nuc_starts buggy.txt | head -3
#ct     st      nuc_starts      nuc_lengths
...
```

[buggy.txt](https://github.com/sstadick/hck/files/10416004/buggy.txt)

**Comment by ghuls** [comment]
Hit the same problem: (column 16 should always be at the end):
```
❯  printf 'col1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\ncol1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\n' 
col1    col2    col3    col4    col5    col6    col7    col8    col9    col10   col11   col12   col13   col14   col15   col16   col17
col1    col2    col3    col4    col5    col6    col7    col8    col9    col10   col11   col12   col13   col14   col15   col16   col17

❯  printf 'col1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\ncol1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\n' | hck -d '\t' -F col8 -F col9 -F col6 -F col11 -F col12 -F col15 -F col17 -F col16
col8    col9    col6    col11   col12   col15   col16   col17
col8    col9    col6    col11   col12   col15   col16   col17

❯  printf 'col1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\ncol1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\n' | hck -d '\t' -F col8 -F col6 -F col11 -F col12 -F col15 -F col17 -F col16
col8    col6    col11   col12   col15   col16   col17
col8    col6    col11   col12   col15   col16   col17

❯  printf 'col1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\ncol1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\n' | hck -d '\t' -F col8 -F col11 -F col12 -F col15 -F col17 -F col16
col8    col11   col12   col15   col16   col17
col8    col11   col12   col15   col16   col17

❯  printf 'col1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\ncol1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\n' | hck -d '\t' -F col8 -F col12 -F col15 -F col17 -F col16
col8    col12   col15   col17   col16
col8    col12   col15   col17   col16

```

**Comment by ghuls** [comment]
It doesn't seem to be related to command line parsing I guess as with -`f` it also outputs it wrong: ```
❯  printf 'col1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\ncol1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\n' | hck -d '\t' -f 8,11,12,15,17,16
col8    col11   col12   col15   col16   col17
col8    col11   col12   col15   col16   col17
```

**Comment by ghuls** [comment]
Repeating `col17` "fixes" it.
```
printf 'col1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\ncol1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\n' | hck -d '\t' -F col8 -F col9 -F col6 -F col11 -F col12 -F col15 -F col17 -F col17 -F col16
col8	col9	col6	col11	col12	col15	col17	col16
col8	col9	col6	col11	col12	col15	col17	col16
```

When col15 and col17 are switched, the output is also correct:
```
❯  printf 'col1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\ncol1\tcol2\tcol3\tcol4\tcol5\tcol6\tcol7\tcol8\tcol9\tcol10\tcol11\tcol12\tcol13\tcol14\tcol15\tcol16\tcol17\n' | hck -d '\t' -F col8 -F col9 -F col6 -F col11 -F col12 -F col17 -F col15 -F col16
col8	col9	col6	col11	col12	col17	col15	col16
col8	col9	col6	col11	col12	col17	col15	col16
```

**Comment by sstadick** [comment]
Yep, this is a bug. I started looking into it but haven't had time to go all in on it yet. I'm pretty sure it's happening here: https://github.com/sstadick/hck/blob/9bf25d33ccd299f1d297afcb4798d86598f31678/src/lib/field_range.rs#L199

Then intent of post-process ranges find duplicate fields, and also to merge ranges of fields together. What is happening is that pop-process is merging two columns together, even though the output order was request to be flipped, and this only seems to happen if the order change isn't in the first 3 or so fields.

I have a test case / branch I'll push shortly. Thank you both for reporting this. If someone gets to fixing this before me I'm always open to PRs!

**Comment by ghuls** [comment]
The merging of ranges is also slightly weird: ```
❯  cargo run -- -f 1-3
    Finished dev [unoptimized + debuginfo] target(s) in 0.47s
     Running `target/debug/hck -f 1-3`
Fields: None
Called Post process: [FieldRange { low: 0, high: 2, pos: 0 }]
Post Sort          : [FieldRange { low: 0, high: 2, pos: 0 }]
Parsed: [FieldRange { low: 0, high: 2, pos: 0 }]
^C

❯  cargo run -- -f 1,2,3
    Finished dev [unoptimized + debuginfo] target(s) in 0.33s
     Running `target/debug/hck -f 1,2,3`
Fields: None
Called Post process: [FieldRange { low: 0, high: 0, pos: 0 }, FieldRange { low: 1, high: 1, pos: 1 }, FieldRange { low: 2, high: 2, pos: 2 }]
Post Sort          : [FieldRange { low: 0, high: 0, pos: 0 }, FieldRange { low: 1, high: 1, pos: 1 }, FieldRange { low: 2, high: 2, pos: 2 }]
Parsed: [FieldRange { low: 0, high: 1, pos: 0 }, FieldRange { low: 2, high: 2, pos: 1 }]
^C

❯  cargo run -- -f 1-4
    Finished dev [unoptimized + debuginfo] target(s) in 0.42s
     Running `target/debug/hck -f 1-4`
Fields: None
Called Post process: [FieldRange { low: 0, high: 3, pos: 0 }]
Post Sort          : [FieldRange { low: 0, high: 3, pos: 0 }]
Parsed: [FieldRange { low: 0, high: 3, pos: 0 }]
^C

❯  cargo run -- -f 1,2,3,4
    Finished dev [unoptimized + debuginfo] target(s) in 0.53s
     Running `target/debug/hck -f 1,2,3,4`
Fields: None
Called Post process: [FieldRange { low: 0, high: 0, pos: 0 }, FieldRange { low: 1, high: 1, pos: 1 }, FieldRange { low: 2, high: 2, pos: 2 }, FieldRange { low: 3, high: 3, pos: 3 }]
Post Sort          : [FieldRange { low: 0, high: 0, pos: 0 }, FieldRange { low: 1, high: 1, pos: 1 }, FieldRange { low: 2, high: 2, pos: 2 }, FieldRange { low: 3, high: 3, pos: 3 }]
Parsed: [FieldRange { low: 0, high: 1, pos: 0 }, FieldRange { low: 2, high: 2, pos: 1 }, FieldRange { low: 3, high: 3, pos: 2 }]
^C

❯  cargo run -- -f 1-30
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
     Running `target/debug/hck -f 1-30`
Fields: None
Called Post process: [FieldRange { low: 0, high: 29, pos: 0 }]
Post Sort          : [FieldRange { low: 0, high: 29, pos: 0 }]
Parsed: [FieldRange { low: 0, high: 29, pos: 0 }]
^C

❯  cargo run -- -f 1-30,31
    Finished dev [unoptimized + debuginfo] target(s) in 0.37s
     Running `target/debug/hck -f 1-30,31`
Fields: None
Called Post process: [FieldRange { low: 0, high: 29, pos: 0 }, FieldRange { low: 30, high: 30, pos: 1 }]
Post Sort          : [FieldRange { low: 0, high: 29, pos: 0 }, FieldRange { low: 30, high: 30, pos: 1 }]
Parsed: [FieldRange { low: 0, high: 30, pos: 0 }]
^C


❯  cargo run -- -f 1-30,31,32
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/hck -f 1-30,31,32`
Fields: None
Called Post process: [FieldRange { low: 0, high: 29, pos: 0 }, FieldRange { low: 30, high: 30, pos: 1 }, FieldRange { low: 31, high: 31, pos: 2 }]
Post Sort          : [FieldRange { low: 0, high: 29, pos: 0 }, FieldRange { low: 30, high: 30, pos: 1 }, FieldRange { low: 31, high: 31, pos: 2 }]
Parsed: [FieldRange { low: 0, high: 30, pos: 0 }, FieldRange { low: 31, high: 31, pos: 1 }]
```

**Comment by sstadick** [comment]
Please see v0.8.0 which fixes this issue
