### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by cyqsimon** [sstadick/hck#68]
Both MIT and Unlicense are included in tree, so I think it would be a good idea to clarify in README whether they are disjunctive (or) or conjunctive (and).

**Comment by sstadick** [comment]
Hi! Thanks for asking, the intent is for it to be `OR`. I will add a clarifying statement in the README and fix the SPDX statement in the cargo.toml. Those will reflect in a future release, but from my viewpoint this has always been an `OR`.

**Comment by sstadick** [comment]
Both changes have been made. Please reopen if there is any remaining ambiguity.
