### ISSUE TITLE
Conda version out of date (v0.7.2)

### ISSUE THREAD

**Issue by mrvollger** [sstadick/hck#70]
Hi @sstadick,

The conda version of hck is out of date with the current releases, and I know conda's CI jobs can take a while but this seems like it might be more than that since the conda version is still on 0.7.2. 

Any chance this could be fixed?
https://anaconda.org/conda-forge/hck

Thanks!
Mitchell

**Comment by sstadick** [comment]
Hello! Thanks for bumping this. CI is failing for conda-forge because the thirdparty license info is out of date and I've been putting off fixing that up. I'll try to get that fixed this week 👍 

https://github.com/conda-forge/hck-feedstock/pull/11

**Comment by mrvollger** [comment]
I took a look at the PR to see if I could help but unfortunately I don't know conda-forge recipe logic. I can barely figure out bioconda most times.. so thanks in advance for working on this, and sorry I couldn't help!

**Comment by mrvollger** [comment]
I know you must be busy but just bumping so it stays on your radar.

**Comment by sstadick** [comment]
Thank you for the bump! I just pushed a maintenance release 0.9.2 that updates deps and hopefully fixes the thing that was failing in conda-forge. I have to wait for conda-forge automation to pick up the new version, but will check back in when it does 👍

**Comment by sstadick** [comment]
Haven't forgotten - conda-forge hasn't auto-picked this up, trying some more routes!

**Comment by sstadick** [comment]
https://github.com/conda-forge/hck-feedstock/pull/13 0.9.2 should land in conda-forge later today.
