### ISSUE TITLE
Missing 0.10.1 tag on github

### ISSUE THREAD

**Issue by TimB87** [sstadick/hck#87]
Hi @sstadick 

I wonder if you can add a tag for https://github.com/sstadick/hck/commit/a17eeb927b8a4e5d573c0bfb2e0d0e952c10f930?

Thanks!

**Comment by sstadick** [comment]
Tag pushed! Not sure how that got missed the last update. Sorry about that! I'll close this out once the publish workflow finishes.

**Comment by TimB87** [comment]
Cool, thanks! :+1:
